### ISSUE TITLE
[help] Database schema

### ISSUE THREAD

**Issue by fabiojansenbr** [adityar224/Timberr#1]
Hello. I'm studying subase with flutter + getx and I really liked your project. Could you provide the database schema this project? Thanks

**Comment by adityar224** [comment]
Hey, I would be updating the `README.md` file soon. I would make sure to throw in the database schema as well.

**Comment by fabiojansenbr** [comment]
Nice. Thanks

**Comment by adityar224** [comment]
I would be opening a different repo for this app for publicity reasons. It would mostly be named Flutter Furniture App. Please follow for updates there and I would defo be uploading the database scheme as well..
